### ISSUE TITLE
locked in ebon hawk

### ISSUE THREAD

**Issue by AlienEffigy** [KOTORCommunityPatches/TSL_Community_Patch#57]
idk what can be done but after i beat narshadaa i didn't get all the cutscenes and my game bugged and i got locked in my ship and the travel terminal wouldn't work so i warped to another planet and did some quests came back to my ship travel terminal was working again but i still get locked in my ship i have done everything i have seen to fix it and nothing has worked and i would rather not start over

**Comment by StellarExile** [comment]
I don't really think the GitHub repository is the place for troubleshooting. I'd suggest going to the [subreddit](https://www.reddit.com/r/kotor/new/). Good luck!
