### ISSUE TITLE
Stuck in place forever by controlling a party member at the start of the Rebuilt Enclave

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/TSL_Community_Patch#58]
[Reported on Deadly Stream](https://deadlystream.com/topic/8213-bug-reports-for-tslrcm-185/?do=findComment&comment=79705)

Upon entering 650DAN with Kreia and another party member, if you trigger the dialogue between Kreia and the player while controlling that other party member, the player gets stuck in place and the cutscene does not progress.

**Comment by DarthParametric** [comment]
Curious, but presumably resolvable with a `SetPartyLeader`.

**Comment by JCarter426** [comment]
Fixed in TSLRCM v1.8.6, so there's no need for us to do anything. Lovely.
