### ISSUE TITLE
Nar Shaddaa Vogga the Hutt model looks transparent/wrong 

### ISSUE THREAD

**Issue by tronotized** [KOTORCommunityPatches/TSL_Community_Patch#61]
In Nar Shaddaa, Vogga the Hutt looks wrong. Here are two screenshots to show what the model looks like in my game. 
![20210117102342_1](https://user-images.githubusercontent.com/77581458/104849385-fdc48280-58ae-11eb-92ab-443be28025c9.jpg)
![20210117102405_1](https://user-images.githubusercontent.com/77581458/104849389-0452fa00-58af-11eb-9543-533cf21d70a0.jpg)

**Comment by DarthParametric** [comment]
This is not a K2CP issue. You are either using a texture mod that lacks the proper TXI, or your GPU doesn't handle envmaps properly.
